# Setup
title:               UCSB Collaboratory
tagline:             'Build your technology repertoire'
description:         'A site to explore different technological themes such as twarc.'
url:                 'https://ucsb-collaboratory.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Amelia Meyer
  url:               ameliameyer.github.io
  email:             ameliameyer@ucsb.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
